server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${APPLICATION_NAME:bank_rest-main}

  datasource:
    url     : ${DB_URL:jdbc:postgresql://localhost:5432/bank_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml

jwt:
  secret    : ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000

encryption:
  secret: ${ENCRYPTION_SECRET:8xK!mP9qR0sT2uV4wY6zA1cE3gH5jL7nQ9}